### ISSUE TITLE
Paper related to the code.

### ISSUE THREAD

**Issue by Pythagoras19** [ToadRedCarp/adaptive-critic-designs#1]
Hello, 

First of all thank you for the nice code. Is there a paper which contains the description and results of the algorithms that are used? for example, the block diagrams. I couldn't find any in the description. 

Regards,

**Comment by gitwilliam** [comment]
Pythagoras19:

It has been awhile since we worked on this.  Hopefully this presentation that I have attached will be helpful.

[Cart-Pole Control.pptx](https://github.com/ToadRedCarp/adaptive-critic-designs/files/2098113/Cart-Pole.Control.pptx)

**Comment by Pythagoras19** [comment]
The block diagrams are exactly what I was looking for, thanks a lot.

**Comment by Pythagoras19** [comment]
Hi, 

this question might be trivial, but can I ask why in order to determine the force to the cart you did this calculation in the model.m function?

% Determine the push to the cart
force=FORCE_MAG*tanh(100*ft); 

Kind Regards,

**Comment by Pythagoras19** [comment]
Regarding my previous question, there is no intermediate value like 0 for the force I assume. It only either maximum force in positive direction or in negative direction.
